version: "3.3"

services:

  hugo:
    build:
      context: https://github.com/gohugoio/hugo.git
    volumes:
      - ./:/site
    working_dir: /site/src
    ports:
      - ${HUGO_SERVER_PORT}:${HUGO_SERVER_PORT}
    command: server --bind 0.0.0.0 --port ${HUGO_SERVER_PORT}

  npm:
    image: node:14.8
    volumes:
      - ./:/site
    working_dir: /site/src/themes/hugo-theme-learn/_src
    entrypoint: npm
