name: Broken links
on:
  push:
jobs:
  check:
    name: Check broken links
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Build devdoc
        run: |
          cp .env.example .env
          docker-compose -f docker-compose.yml up --build -d
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          HUGO_SERVER_PORT: "1313"

      - name: Wait 60 seconds
        uses: juliangruber/sleep-action@v1
        with:
          time: 60s

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install 'Broken link checker' on external links
        run: npm install broken-link-checker -g

      - name: Run tests
        run: blc ${{ env.SERVER }} -iro
